from typing import Protocol
from uuid import UUID

from .entities import MenuItem, TableOrder, User, Restaurant, RestaurantTable


class IUserRepository(Protocol):
    async def create(self, user: User) -> User: ...
    async def get_by_id(self, id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_username(self, username: str) -> User | None: ...
    async def list_all(self) -> list[User]: ...
    async def list_by_restaurant(self, restaurant_id: UUID) -> list[User]: ...
    async def update(self, user: User) -> User: ...
    async def delete(self, id: UUID) -> None: ...


class IRestaurantRepository(Protocol):
    async def create(self, restaurant: Restaurant) -> Restaurant: ...
    async def get_by_id(self, id: UUID) -> Restaurant | None: ...
    async def list_all(self) -> list[Restaurant]: ...
    async def update(self, restaurant: Restaurant) -> Restaurant: ...
    async def delete(self, id: UUID) -> None: ...


class ITableRepository(Protocol):
    async def create(self, table: RestaurantTable) -> RestaurantTable: ...
    async def get_by_id(self, id: UUID) -> RestaurantTable | None: ...
    async def list_by_restaurant(self, restaurant_id: UUID) -> list[RestaurantTable]: ...
    async def update(self, table: RestaurantTable) -> RestaurantTable: ...
    async def delete(self, id: UUID) -> None: ...


class IMenuRepository(Protocol):
    async def create(self, item: MenuItem) -> MenuItem: ...
    async def get_by_id(self, id: UUID) -> MenuItem | None: ...
    async def list_by_restaurant(self, restaurant_id: UUID) -> list[MenuItem]: ...
    async def update(self, item: MenuItem) -> MenuItem: ...
    async def delete(self, id: UUID) -> None: ...


class ITableOrderRepository(Protocol):
    async def create(self, order: TableOrder) -> TableOrder: ...
    async def get_by_id(self, id: UUID) -> TableOrder | None: ...
    async def list_by_table(self, table_id: UUID) -> list[TableOrder]: ...
    async def update(self, order: TableOrder) -> TableOrder: ...
    async def delete(self, id: UUID) -> None: ...
